# Generated by Django 5.1.3 on 2024-12-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_distrct',
            new_name='tbl_district',
        ),
    ]
