# Generated by Django 5.1.3 on 2025-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_transportationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_photo', models.FileField(upload_to='Assets/user/photo/')),
                ('vehicle_count', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
            ],
        ),
    ]
