# Generated by Django 5.1.3 on 2025-03-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
