# Generated by Django 5.1.3 on 2025-01-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=50)),
                ('reg_email', models.CharField(max_length=50)),
                ('reg_address', models.CharField(max_length=50)),
                ('reg_password', models.CharField(max_length=50)),
                ('reg_district', models.CharField(max_length=50)),
                ('reg_place', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assests/user/photo/')),
            ],
        ),
    ]
