# Generated by Django 5.1.3 on 2025-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_driver_tbl_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_driver',
            name='driver_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_employee',
            name='employee_status',
            field=models.IntegerField(default=0),
        ),
    ]
