# Generated by Django 5.2 on 2025-04-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_vehicle_tbl_cabassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cabassign',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_vehicle'),
        ),
    ]
