# Generated by Django 5.2 on 2025-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_cabassign_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cabassign',
            name='cabassign_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
