# Generated by Django 5.2 on 2025-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_cabassign_cabassign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cabassign',
            name='cabassign_status',
            field=models.IntegerField(default=0),
        ),
    ]
