# Generated by Django 5.2 on 2025-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_cabassign_cabassign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cabassign',
            name='email_status',
            field=models.IntegerField(default=0),
        ),
    ]
