# Generated by Django 5.1.3 on 2025-03-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
