# Generated by Django 5.1.3 on 2025-03-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_alter_tbl_driver_driver_status_and_more'),
        ('User', '0002_delete_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.CharField(max_length=50)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_emergencypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergencypass_amount', models.CharField(max_length=50)),
                ('emergencypass_fromplace', models.CharField(max_length=50)),
                ('emergencypass_toplace', models.CharField(max_length=50)),
                ('emergencypass_validity', models.CharField(max_length=50)),
                ('emergencypass_status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_passrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passrequest_date', models.CharField(max_length=50)),
                ('passrequest_amount', models.CharField(max_length=50)),
                ('passrequest_startdate', models.CharField(max_length=50)),
                ('passrequest_enddate', models.CharField(max_length=50)),
                ('passrequest_status', models.IntegerField(default=0)),
                ('passrequest_fromplace', models.CharField(max_length=50)),
                ('passrequest_toplace', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_count', models.CharField(max_length=50)),
                ('rating_content', models.CharField(max_length=50)),
                ('rating_datetime', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rentvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvehicle_number', models.CharField(max_length=50)),
                ('rentvehicle_amount', models.CharField(max_length=50)),
                ('rentvehicle_status', models.IntegerField(default=0)),
                ('rentvehicle_startdate', models.CharField(max_length=50)),
                ('rentvehicle_enddate', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
    ]
