# Generated by Django 5.1.3 on 2025-03-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_vehicle'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_emergencypass',
            name='emergencypass_fromplace',
        ),
        migrations.RemoveField(
            model_name='tbl_emergencypass',
            name='emergencypass_toplace',
        ),
        migrations.AddField(
            model_name='tbl_emergencypass',
            name='from_place',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='Admin.tbl_place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_emergencypass',
            name='to_place',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='Admin.tbl_place'),
            preserve_default=False,
        ),
    ]
