# Generated by Django 5.1.7 on 2025-03-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_vehicle'),
        ('User', '0005_alter_tbl_emergencypass_emergencypass_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_passrequest',
            name='passrequest_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_passrequest',
            name='passrequest_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_passrequest',
            name='passrequest_fromplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passrequest_fromplace', to='Admin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_passrequest',
            name='passrequest_startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_passrequest',
            name='passrequest_toplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passrequest_toplace', to='Admin.tbl_place'),
        ),
    ]
