# Generated by Django 5.1.3 on 2025-04-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_vehicle_tbl_cabassign'),
        ('User', '0007_delete_tbl_rentvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentvehicle_number', models.CharField(max_length=50)),
                ('rentvehicle_amount', models.CharField(max_length=50)),
                ('rentvehicle_status', models.IntegerField(default=0)),
                ('rentvehicle_startdate', models.CharField(max_length=50)),
                ('rentvehicle_enddate', models.CharField(max_length=50)),
                ('rentvehicle_proof', models.FileField(upload_to='Assets/Rentvehicle/Proof')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee')),
            ],
        ),
    ]
