# Generated by Django 5.2 on 2025-04-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_cabassign_cabassign_status'),
        ('User', '0009_alter_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_employee'),
        ),
    ]
