# Generated by Django 5.2 on 2025-04-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tbl_feedback_driver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
