# Generated by Django 5.2 on 2025-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_passrequest',
            name='email_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_rentvehicle',
            name='email_status',
            field=models.IntegerField(default=0),
        ),
    ]
